name: Kubernetes Hardening Scan
description: Container Hardening Validation
inputs:
  namespaces:
    type: string
  # chart-path:
  #   type: string
runs:
  using: "composite"
  steps:
    - name: Install Kubescape
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash

    - name: Scan with Kubescape (NSA + MITRE + PSS)
      shell: bash
      run: |
        export PATH=$PATH:/home/runner/.kubescape/bin
        kubescape scan framework nsa,mitre,devopsbest \
          --include-namespaces ${{ inputs.namespaces }} \
          --scan-images \
          --verbose \
          --format json \
          --output kubescape-results.json \
          --severity-threshold medium \
          --compliance-threshold 50   # (0-100)
      continue-on-error: true

    - name: Upload json as artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        path: kubescape-results.json
        archive: false

    - name: Checkout code
      uses: actions/checkout@v6
      with:
        path: temp/repocode
        persist_credentials: false

    - name: Install Trivy
      uses: aquasecurity/setup-trivy@v0.2.6

    - name: Scan Helm chart with Trivy (misconfigurations + images)
      shell: bash
      working-directory: temp/repocode
      run: |
        trivy config \
          --exit-code 1 \
          --format json \
          --output trivy-results.json \
          .
      continue-on-error: true

    - name: Upload json as artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        path: temp/repocode/trivy-results.json
        archive: false

    - name: Fail on untagged / latest images
      shell: bash
      working-directory: temp/repocode
      run: |
        echo "Checking for untagged or 'latest' images..."
        grep -rE 'image:.*:(latest|[^:]+)$' . --include="*.yaml" --include="*.yml" || echo "No latest images found"
