name: Switch internal references to current branch
run-name: Switch internal refs to ${{ github.ref_name }}
on:
  push:
    branches-ignore:
      - 'main'

permissions:
  contents: write
  actions: write

jobs:
  switch-refs:
    if: github.event.created
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOWS_TOKEN }}

      - name: Set up authentication
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update references
        run: |
          cd ./.github/workflows
          # shellcheck disable=2038
          find . -type f -name '*.yaml' -or -name '*.yml' | \
          xargs sed -i 's|uses: ${{ github.repository }}/\(.*\)@.*|uses: ${{ github.repository }}/\1@v${{ github.ref_name }}|gi'
      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update references to the new branch [skip ci]"
          git push origin "${{ github.ref_name }}"
