name: Add contributors

on:
  workflow_dispatch

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.get_repo_list.outputs.repos }}
    steps:
      - name: Get repo list
        id: get_repo_list
        run: |
          repos=$(gh repo list ${{ github.repository_owner }} -L 200 --json url --jq '.[].url' --jq 'map(.url)| [.[] | sub("https://github.com/";"")]')
          echo "repos=${repos}" >> $GITHUB_OUTPUT
          echo "${{ github.repository_owner }}'s Repositories: ${repos}" >> $GITHUB_STEP_SUMMARY
          echo "${{ github.repository_owner }}'s Repositories: ${repos}"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Show repo list
        run: |
          echo "Repos raw: ${{ steps.get_repo_list.outputs.repos }}"

  show-info:
    needs: [read-config]
    runs-on: ubuntu-latest
    steps:
      - name: Show repo list
        run: |
          echo "Repos raw: ${{ needs.read-config.outputs.repos }}"

# echo "Repos fromJson: ${{ fromJson(needs.read-config.outputs.repos) }}"
# echo "Repos from/toJson: ${{ fromJson(toJson(needs.read-config.outputs.repos)) }}"


  apply:
    needs: [read-config]
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.read-config.outputs.repos) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}

      - name: Check configuration file existence
        run: |
          echo "Repository: ${{ matrix.repo }}" >> $GITHUB_STEP_SUMMARY
          if [ -f ${{ github.workspace }}/.github/contributors1.yaml ]; then
            echo "Configuration file .github/contributors1.yaml exists"
          else
            echo "Configuration file .github/contributors1.yaml does not exist"
            echo "Configuration file .github/contributors1.yaml does not exist in repository ${{ matrix.repo }}" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
      - name: Print collab info
        id: print-collab-info
        run: |
          sudo apt-get update
          sudo apt-get install -y yq
          echo "repo_users=$(yq '.contributors|join(",")' ${{ github.workspace }}/.github/contributors1.yaml)" >> $GITHUB_OUTPUT
          cat ${{ github.workspace }}/.github/contributors1.yaml >> $GITHUB_STEP_SUMMARY
      - name: Print config
        run: |
          echo "Repo: ${{ matrix.repo }}"
          echo "Users: ${{ steps.print-collab-info.outputs.users }}"
      # - name: Run Manager Collaborators Action
      #   id: manager-collaborators-action
      #   uses: gateixeira/manage-collaborators-action@v1.0.1
      #   with:
      #     token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     repositories: ${{ matrix.repo}}
      #     users: ${{ steps.print-collab-info.outputs.users }}
      #     role: push
      #     action: add
