name: Manager contributors

on:
  workflow_dispatch

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.read_config.outputs.repos }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read contributors Configuration File
        id: read_config
        run: |
          repos=$(python3 ${{ github.workspace }}/scripts/read-user-list.py ${{ github.workspace }}/.github/contributors.yaml repos)
          echo "repos=${repos}" >> $GITHUB_OUTPUT


  apply:
    needs: [read-config]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ needs.read-config.outputs.repos }}
    steps:
      - name: Print collab info
        run: |
          echo ${{ matrix.repo }}
          python3 -m pip install pyyaml
          echo "$(python3 ${{ github.workspace }}/scripts/read-user-list.py ${{ github.workspace }}/.github/contributors.yaml users ${{ matrix.repo }})"

    #   - name: Run Manager Collaborators Action
    #     id: manager-collaborators-action
    #     uses: gateixeira/manage-collaborators-action@v1.0.1
    #     with:
    #       token: ${{ secrets.REPO_ACCESS_TOKEN }}
    #       repositories: owner/repo1,owner/repo2
    #       users: user1,user2
    #       role: push
    #       action: add
