name: Manager Collaborators

on:
  workflow_dispatch

jobs:
  manager-collaborators:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read Collaborators Configuration File
        id: read-collaborators-configuration
        uses: nichmor/minimal-read-yaml@v0.0.2
        with:
          config: ${{ github.workspace }}/.github/collaborators.yaml

      - name: Print collab info
        run: |
          for i in ${{ steps.read-collaborators-configuration.outputs }}; do
            echo ${i}
          done
#          echo "${{ steps.read-collaborators-configuration.outputs.collaborators }}"
#          echo "${{ join(fromJson(steps.read-collaborators-configuration.outputs.collaborators.repository), ',') }}"

    #   - name: Run Manager Collaborators Action
    #     id: manager-collaborators-action
    #     uses: gateixeira/manage-collaborators-action@v1.0.1
    #     with:
    #       token: ${{ secrets.REPO_ACCESS_TOKEN }}
    #       repositories: owner/repo1,owner/repo2
    #       users: user1,user2
    #       role: push
    #       action: add
