---

name: Check tag existence

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to check'
        required: true
        default: 'v1.0.0'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag exists
        id: check_tag
        uses: actions/github-script@v6
        with:
          script: |
            const tag = '${{ github.event.inputs.tag }}';
            const { data: tags } = await github.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const exists = tags.some(t => t.name === tag);
            core.setOutput('exists', exists);

            if (exists) {
              await github.rest.actions.createWorkflowRunSummary({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId,
                text: `The tag "${tag}" exists.`
              });
            } else {
              await github.rest.actions.createWorkflowRunSummary({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId,
                text: `The tag "${tag}" does not exist.`
              });
            }
