---

name: Check tag existence

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to check'
        required: true
        default: 'v1.0.0'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag exists
        id: check_tag
        uses: actions/github-script@v7
        with:
          script: |
            const tag = '${{ github.event.inputs.tag }}';
            const { data: tags } = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const exists = tags.some(t => t.name === tag);
            core.setOutput('exists', exists);

            if (exists) {
              await core.summary
                .addHeading('Tag Check Result')
                .addCodeBlock(`✅ The tag "${tag}" exists.`, "js")
                .addRaw('Tag exists')
                .write();
            } else {
              await core.summary
                .addHeading('Tag Check Result')
                .addCodeBlock(`❌ The tag "${tag}" does not exist.`, "js")
                .addRaw('Tag does not exist')
                .write();
            }
  tag-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Summary"
        run: |
          echo "Event: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "Actor: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "Inputs: ${{ toJson(github.event.inputs) }}" >> $GITHUB_STEP_SUMMARY
      - name: Check tag existence
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@main
        with:
          tag-name: ${{ github.event.inputs.tag }}
          ref: ${{ github.ref }}
          check-tag: true
          create-tag: false
