on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version type to release (patch, minor, major)"
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'
        required: true

name: Create Workflow-Hub GitHub release
run-name: "Workflow-Hub GitHub release type ${{ inputs.version }}"
permissions:
  contents: read

jobs:
  check-tag:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get latest release via GitHub API
        id: generate_version
        env:
          VERSION_TYPE: ${{ inputs.version }}
        run: |
          RESPONSE=$(curl -s \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest)

          LATEST_TAG=$(echo "$RESPONSE" | jq -r .tag_name)
          echo "LATEST_TAG=$LATEST_TAG"

          # Extract the version number from the latest tag
          LATEST_VERSION=$(echo "$LATEST_TAG" | cut -d'v' -f2)

          # Increment the version number based on the version type
          MAJOR=$(echo $LATEST_VERSION | cut -d'.' -f1)
          echo "MAJOR=$MAJOR"
          MINOR=$(echo $LATEST_VERSION | cut -d'.' -f2)
          echo "MINOR=$MINOR"
          PATCH=$(echo $LATEST_VERSION | cut -d'.' -f3)
          echo "PATCH=$PATCH"
          case "$VERSION_TYPE" in
            "patch")
              echo "version type hit: patch"
              let "PATCH++"
              ;;
            "minor")
              echo "version type hit: minor"
              let "MINOR++"
              PATCH="0"
              ;;
            "major")
              echo "version type hit: major"
              let "MAJOR++"
              MINOR="0"
              PATCH="0"
              ;;
          esac
          echo "Create a new version"
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"

          # Output the new version
          echo "New version: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Release Version: $NEW_VERSION" >> $GITHUB_STEP_SUMMARY

      - name: Check if tag exists
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@v2.1.2
        with:
          tag-name: "v${{ steps.generate_version.outputs.version }}"
          ref: ${{ github.ref }}
          create-tag: false
          check-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-preparation:
    needs: [check-tag]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.check-tag.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: true
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Set up authentication
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          ACTOR: ${{ github.actor }}
          REPOSITORY: ${{ github.repository }}
        run: |
          git config --global user.name "$ACTOR"
          git config --global user.email "$ACTOR@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$REPOSITORY

      - name: Create Release Branch
        run: |
          git checkout -b "release/v$VERSION"
          git push origin "release/v$VERSION"

      - name: Update references
        run: |
          # shellcheck disable=2038
          find . -type f \( -name '*.yaml' -o -name '*.yml' -o -name '*.md' \) ! -name 'github-release.yml' \
          | xargs sed -i "s|uses: netcracker/qubership-workflow-hub/\(.*\)@main|uses: netcracker/qubership-workflow-hub/\1@v${VERSION}|gi"

      - name: Commit and push changes
        env:
          ACTOR: ${{ github.actor }}
        run: |
          git config --global user.name "$ACTOR"
          git config --global user.email "$ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Update references to the new version"
          git push origin "release/v$VERSION"
          git tag "v$VERSION"
          git push origin "v$VERSION"

  create-github-release:
    needs: [check-tag, release-preparation]
    permissions:
      contents: write
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
    with:
      version: ${{ needs.check-tag.outputs.version }}
      publish: false
      config-name: release-drafter.yml
