name: Say Goodby
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run'
        required: false
        type: boolean
        default: false

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: echo ${{ (github.event.inputs.dry-run && 'Dry Run') || 'Not Dry Run' }}

