---

name: "Add commit messages to PR body"

on:
    pull_request:
        types: [opened, synchronize, edited]

permissions:
    pull-requests: write

jobs:
    update-pr-body:
        runs-on: ubuntu-latest
        steps:
            - name: "Update PR body"
              uses: borislavr/qubership-workflow-hub/actions/pr-add-messages@main
