name: Kubernetes Hardening & Security Scan

on:
  workflow_call:
    inputs:
      chart-path:
        type: string
        description: Path to chart

permissions:
  contents: read
  # security-events: write

jobs:
  hardening-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Hardening Scan
        uses: borislavr/qubership-workflow-hub/actions/k8s-hardening-scan@main
